import exceptiontest

try:
    exceptiontest.run()
except Exception as err:
    print(err)